

services:
  app:
    build: .
    container_name: employee-app
    ports:
        - "8080:8080"
    depends_on:
        mysql:
          condition: service_healthy
    networks:
      - emp-network

  mysql:
    image: mysql:8.0
    container_name: employee-mysql
    environment:
      MYSQL_USER: pratham
      MYSQL_PASSWORD: Dellg3@5816
      MYSQL_ROOT_PASSWORD: Dellg3@5816
      MYSQL_DATABASE: employee_db
    ports:
      - "3307:3306"
    networks:
      - emp-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
        - mysql-data:/var/lib/mysql

networks:
    emp-network:
      driver: bridge

volumes:
  mysql-data:   # To save mysql data even if container is removed or recreated!